# 빅데이터 분석 특강 (3주차) 3월 21일 

- toc:true
- branch: master
- badges: true
- comments: false
- author: 최서연
- categories: [Special Topics in Big Data Analysis, TensorFlow, TensorFlow NumPy]

### 학부 수업 중 데이터과학 수업 참고하세요~

### imports 

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
tf.config.experimental.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

### 지난강의 보충 

`-` max, min, sum, mean 

In [3]:
a = tf.constant([1.0,2.0,3.0,4.0])
a

2022-03-21 20:26:04.675110: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-03-21 20:26:05.130559: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 22288 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3090, pci bus id: 0000:65:00.0, compute capability: 8.6


<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1., 2., 3., 4.], dtype=float32)>

In [4]:
max(a)

<tf.Tensor: shape=(), dtype=float32, numpy=4.0>

In [5]:
mean(a)

NameError: name 'mean' is not defined

는 오류남

소수점 추가해서 int를 float으로 바꿔~

int 자체에서 계산하면 평균이 2로 나옴

In [ ]:
tf.reduce_mean(a)

나중에 tnp활용해서 numpy처럼 쓰자

#### concat, stack 

`-` 예제: (2,3,4,5) stack (2,3,4,5) -> (?,?,?,?,?) 

In [6]:
a = tf.reshape(tf.constant(range(2*3*4*5)),(2,3,4,5))
b = -a

(2,3,4,5) =  (1,2,3,4,5)

**case1** (1,2,3,4,5) stack (1,2,3,4,5) = (2,2,3,4,5) # axis = 0

In [7]:
tf.stack([a,b],axis=0)

<tf.Tensor: shape=(2, 2, 3, 4, 5), dtype=int32, numpy=
array([[[[[   0,    1,    2,    3,    4],
          [   5,    6,    7,    8,    9],
          [  10,   11,   12,   13,   14],
          [  15,   16,   17,   18,   19]],

         [[  20,   21,   22,   23,   24],
          [  25,   26,   27,   28,   29],
          [  30,   31,   32,   33,   34],
          [  35,   36,   37,   38,   39]],

         [[  40,   41,   42,   43,   44],
          [  45,   46,   47,   48,   49],
          [  50,   51,   52,   53,   54],
          [  55,   56,   57,   58,   59]]],


        [[[  60,   61,   62,   63,   64],
          [  65,   66,   67,   68,   69],
          [  70,   71,   72,   73,   74],
          [  75,   76,   77,   78,   79]],

         [[  80,   81,   82,   83,   84],
          [  85,   86,   87,   88,   89],
          [  90,   91,   92,   93,   94],
          [  95,   96,   97,   98,   99]],

         [[ 100,  101,  102,  103,  104],
          [ 105,  106,  107,  108,  109],
         

**case2** (2,1,3,4,5) stack (2,1,3,4,5) = (2,2,3,4,5) # axis = 1
- 늘어나는 차원의 축을 몇 번째에 넣을 것인가.

In [8]:
tf.stack([a,b],axis=1)

<tf.Tensor: shape=(2, 2, 3, 4, 5), dtype=int32, numpy=
array([[[[[   0,    1,    2,    3,    4],
          [   5,    6,    7,    8,    9],
          [  10,   11,   12,   13,   14],
          [  15,   16,   17,   18,   19]],

         [[  20,   21,   22,   23,   24],
          [  25,   26,   27,   28,   29],
          [  30,   31,   32,   33,   34],
          [  35,   36,   37,   38,   39]],

         [[  40,   41,   42,   43,   44],
          [  45,   46,   47,   48,   49],
          [  50,   51,   52,   53,   54],
          [  55,   56,   57,   58,   59]]],


        [[[   0,   -1,   -2,   -3,   -4],
          [  -5,   -6,   -7,   -8,   -9],
          [ -10,  -11,  -12,  -13,  -14],
          [ -15,  -16,  -17,  -18,  -19]],

         [[ -20,  -21,  -22,  -23,  -24],
          [ -25,  -26,  -27,  -28,  -29],
          [ -30,  -31,  -32,  -33,  -34],
          [ -35,  -36,  -37,  -38,  -39]],

         [[ -40,  -41,  -42,  -43,  -44],
          [ -45,  -46,  -47,  -48,  -49],
         

**case3** (2,3,1,4,5) stack (2,3,1,4,5) = (2,3,2,4,5) # axis = 2

In [9]:
tf.stack([a,b],axis=2)

<tf.Tensor: shape=(2, 3, 2, 4, 5), dtype=int32, numpy=
array([[[[[   0,    1,    2,    3,    4],
          [   5,    6,    7,    8,    9],
          [  10,   11,   12,   13,   14],
          [  15,   16,   17,   18,   19]],

         [[   0,   -1,   -2,   -3,   -4],
          [  -5,   -6,   -7,   -8,   -9],
          [ -10,  -11,  -12,  -13,  -14],
          [ -15,  -16,  -17,  -18,  -19]]],


        [[[  20,   21,   22,   23,   24],
          [  25,   26,   27,   28,   29],
          [  30,   31,   32,   33,   34],
          [  35,   36,   37,   38,   39]],

         [[ -20,  -21,  -22,  -23,  -24],
          [ -25,  -26,  -27,  -28,  -29],
          [ -30,  -31,  -32,  -33,  -34],
          [ -35,  -36,  -37,  -38,  -39]]],


        [[[  40,   41,   42,   43,   44],
          [  45,   46,   47,   48,   49],
          [  50,   51,   52,   53,   54],
          [  55,   56,   57,   58,   59]],

         [[ -40,  -41,  -42,  -43,  -44],
          [ -45,  -46,  -47,  -48,  -49],
       

**case4** (2,3,4,1,5) stack (2,3,4,1,5) = (2,3,4,2,5) # axis = 3

In [10]:
tf.stack([a,b],axis=3)

<tf.Tensor: shape=(2, 3, 4, 2, 5), dtype=int32, numpy=
array([[[[[   0,    1,    2,    3,    4],
          [   0,   -1,   -2,   -3,   -4]],

         [[   5,    6,    7,    8,    9],
          [  -5,   -6,   -7,   -8,   -9]],

         [[  10,   11,   12,   13,   14],
          [ -10,  -11,  -12,  -13,  -14]],

         [[  15,   16,   17,   18,   19],
          [ -15,  -16,  -17,  -18,  -19]]],


        [[[  20,   21,   22,   23,   24],
          [ -20,  -21,  -22,  -23,  -24]],

         [[  25,   26,   27,   28,   29],
          [ -25,  -26,  -27,  -28,  -29]],

         [[  30,   31,   32,   33,   34],
          [ -30,  -31,  -32,  -33,  -34]],

         [[  35,   36,   37,   38,   39],
          [ -35,  -36,  -37,  -38,  -39]]],


        [[[  40,   41,   42,   43,   44],
          [ -40,  -41,  -42,  -43,  -44]],

         [[  45,   46,   47,   48,   49],
          [ -45,  -46,  -47,  -48,  -49]],

         [[  50,   51,   52,   53,   54],
          [ -50,  -51,  -52,  -53,  -54

**case5** (2,3,4,5,1) stack (2,3,4,5,1) = (2,3,4,5,2) # axis = 4

In [11]:
tf.stack([a,b],axis=-1)

<tf.Tensor: shape=(2, 3, 4, 5, 2), dtype=int32, numpy=
array([[[[[   0,    0],
          [   1,   -1],
          [   2,   -2],
          [   3,   -3],
          [   4,   -4]],

         [[   5,   -5],
          [   6,   -6],
          [   7,   -7],
          [   8,   -8],
          [   9,   -9]],

         [[  10,  -10],
          [  11,  -11],
          [  12,  -12],
          [  13,  -13],
          [  14,  -14]],

         [[  15,  -15],
          [  16,  -16],
          [  17,  -17],
          [  18,  -18],
          [  19,  -19]]],


        [[[  20,  -20],
          [  21,  -21],
          [  22,  -22],
          [  23,  -23],
          [  24,  -24]],

         [[  25,  -25],
          [  26,  -26],
          [  27,  -27],
          [  28,  -28],
          [  29,  -29]],

         [[  30,  -30],
          [  31,  -31],
          [  32,  -32],
          [  33,  -33],
          [  34,  -34]],

         [[  35,  -35],
          [  36,  -36],
          [  37,  -37],
          [  38, 

`-` 예제: (2,3,4), (2,3,4), (2,3,4)

In [12]:
a = tf.reshape(tf.constant(range(2*3*4)),(2,3,4))
b = -a
c = 2*a

(예시1) (2,3,4), (2,3,4), (2,3,4) $\to$ (6,3,4) # 첫번째 축이 바뀐다는 뜻이지,
- 차원이 같으니 stack 이 아니라 concat을 쓰자!

In [13]:
tf.concat([a,b,c],axis=0).shape

TensorShape([6, 3, 4])

(예시2) (2,3,4), (2,3,4), (2,3,4) $\to$ (2,9,4)

In [14]:
tf.concat([a,b,c],axis=1).shape

TensorShape([2, 9, 4])

(예시3) (2,3,4), (2,3,4), (2,3,4) $\to$ (2,3,12)

In [15]:
tf.concat([a,b,c],axis=-1).shape

TensorShape([2, 3, 12])

(예시4) (2,3,4), (2,3,4), (2,3,4) $\to$ (3,2,3,4) # 차원이 수정돼? stack을 쓰자
- 차원 늘어난 거 첫번째로 놓고
- 두 번째 자리에 축을 넣은 것으로 보자

In [16]:
tf.stack([a,b,c],axis=0).shape

TensorShape([3, 2, 3, 4])

(예시5) (2,3,4), (2,3,4), (2,3,4) $\to$ (2,3,3,4)

In [17]:
tf.stack([a,b,c],axis=1).shape

TensorShape([2, 3, 3, 4])

(예시6) (2,3,4), (2,3,4), (2,3,4) $\to$ (2,3,3,4) 

In [18]:
tf.stack([a,b,c],axis=2).shape

TensorShape([2, 3, 3, 4])

(예시7) (2,3,4), (2,3,4), (2,3,4) $\to$ (2,3,4,3) 

In [19]:
tf.stack([a,b,c],axis=-1).shape

TensorShape([2, 3, 4, 3])

`-` 예제: (2,3,4) (4,3,4) $\to$ (6,3,4) 
- 차원 두 개, concat쓰자

In [20]:
a = tf.reshape(tf.constant(range(2*3*4)),(2,3,4))
b = tf.reshape(-tf.constant(range(4*3*4)),(4,3,4))

In [21]:
a.shape

TensorShape([2, 3, 4])

In [22]:
b.shape

TensorShape([4, 3, 4])

In [23]:
tf.concat([a,b],axis=0).shape

TensorShape([6, 3, 4])

In [24]:
tf.concat([a,b],axis=1).shape

InvalidArgumentError: ConcatOp : Dimensions of inputs should match: shape[0] = [2,3,4] vs. shape[1] = [4,3,4] [Op:ConcatV2] name: concat

In [25]:
tf.concat([a,b],axis=2).shape

InvalidArgumentError: ConcatOp : Dimensions of inputs should match: shape[0] = [2,3,4] vs. shape[1] = [4,3,4] [Op:ConcatV2] name: concat

차원이 다르기 때문에 에러가 뜬다.

`-` (2,2) @ (2,) 의 연산? 

**numpy**

In [26]:
np.array([[1,0],[0,1]]) @ np.array([77,-88])

array([ 77, -88])

In [27]:
np.array([77,-88]) @ np.array([[1,0],[0,1]])

array([ 77, -88])

(2,)는 길이가 2일 벡터일 뿐이니까 알아서 행이나 열 행렬로 인식해서 계산한다.

In [28]:
np.array([[1,0],[0,1]]) @ np.array([77,-88]).reshape(2,1)

array([[ 77],
       [-88]])

In [29]:
 np.array([77,-88]).reshape(2,1) @ np.array([[1,0],[0,1]])

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 1)

(2,1)로 사이즈를 명시해주고 계산하면 ㅔ러가 뜬다.

In [30]:
 np.array([77,-88]).reshape(1,2) @ np.array([[1,0],[0,1]])

array([[ 77, -88]])

tf.constant는 행, 열 구분 후 알아서 계산해주지 않는다.

**tensorflow**

In [31]:
I = tf.constant([[1.0,0.0],[0.0,1.0]])
x = tf.constant([77.0,-88.0])

In [32]:
x @ I

InvalidArgumentError: In[0] and In[1] has different ndims: [2] vs. [2,2] [Op:MatMul]

In [33]:
x

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 77., -88.], dtype=float32)>

In [34]:
I

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 0.],
       [0., 1.]], dtype=float32)>

In [35]:
tf.reshape

<function tensorflow.python.ops.array_ops.reshape(tensor, shape, name=None)>

In [36]:
tf.reshape(x,-1)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 77., -88.], dtype=float32)>

In [37]:
I @ tf.reshape(x,(2,1))

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[ 77.],
       [-88.]], dtype=float32)>

In [38]:
tf.reshape(x,(2,1)) @ I

InvalidArgumentError: Matrix size-incompatible: In[0]: [2,1], In[1]: [2,2] [Op:MatMul]

---

### tf.Variable

#### 선언 

`-` tf.Variable()로 선언

In [39]:
tf.Variable([1,2,3,4])

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [40]:
tf.Variable([1.0,2.0,3.0,4.0])

<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([1., 2., 3., 4.], dtype=float32)>

`-` tf.constant() 선언후 변환

In [41]:
_a = tf.Variable([1,2,3,4])
type(_a)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [42]:
tf.Variable(tf.constant([1,2,3,4]))

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

`-` np 등으로 선언후 변환 

In [43]:
tf.Variable(np.array([1,2,3,4]))

<tf.Variable 'Variable:0' shape=(4,) dtype=int64, numpy=array([1, 2, 3, 4])>

#### 타입

In [44]:
type(tf.constant([1,2,3,4]))

tensorflow.python.framework.ops.EagerTensor

#### 인덱싱 

In [45]:
a = tf.Variable([1,2,3,4])
a

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [46]:
a[:2]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [47]:
type(a[:2]) # tf.constant랑 같은 타입

tensorflow.python.framework.ops.EagerTensor

#### 연산가능 

In [48]:
a = tf.Variable([1,2,3,4])
b = -a

In [49]:
type(b)

tensorflow.python.framework.ops.EagerTensor

b는 constant와 같은 자료형으로 정의

In [50]:
a = tf.Variable([1,2,3,4])
b = tf.Variable([-1,-2,-3,-4])

In [51]:
type(a)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [52]:
type(b)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [53]:
a+b

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 0, 0, 0], dtype=int32)>

In [54]:
type(a+b)

tensorflow.python.framework.ops.EagerTensor

연산하니 자료형이 바뀐다.

#### tf.Variable도 쓰기 불편함 

In [55]:
tf.Variable([1,2]) + tf.Variable([3.14,3.14])

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a int32 tensor but is a float tensor [Op:AddV2]

에러나

#### tnp의 은총도 일부만 가능 

In [56]:
import tensorflow.experimental.numpy as tnp
tnp.experimental_enable_numpy_behavior()

`-` 알아서 형 변환 

In [57]:
tf.Variable([1,2]) + tf.Variable([3.14,3.14])

<tf.Tensor: shape=(2,), dtype=float64, numpy=array([4.1400001, 5.1400001])>

`-` .reshape 메소드 

In [58]:
tf.Variable([1,2,3,4]).reshape(2,2)

AttributeError: 'ResourceVariable' object has no attribute 'reshape'

이건 tnp에서 되지 않음

#### 대부분의 동작은 tf.constant랑 큰 차이를 모르겠음 

`-` tf.concat 

자료형 변환 안 되게 각각 선언해주기

In [59]:
a = tf.Variable([[1,2],[3,4]])
b = tf.Variable([[-1,-2],[-3,-4]])
tf.concat([a,b],axis=0)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 1,  2],
       [ 3,  4],
       [-1, -2],
       [-3, -4]], dtype=int32)>

어 tensor네

`-` tf.stack

In [60]:
a = tf.Variable([[1,2],[3,4]])
b = tf.Variable([[-1,-2],[-3,-4]])
tf.stack([a,b],axis=0)

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4]],

       [[-1, -2],
        [-3, -4]]], dtype=int32)>

- 연산하면 바뀌는 자료형 

#### 변수값변경가능(?)

In [61]:
a=1
id(a)

139930265272560

In [62]:
a=45
id(a)

139930265273968

1이라고 저장되었던 a를 다시 값을 주면 재할당의 개념.
- 메모리 주소가 바뀐 것.
- 주소가 같다면 편집의 개념이 되겠지
- tf.constant 로 할당해주면 메모리 주소에 있는 것을 바꿀 수 없다.(불변!)
- 가변형을 만들어야 하는 이유..
    - 불변형을 여러개 쓰면 메모리가 많이 필요
    - 한정된 변수 개수를 가지고 있다면 더 힘들어
- GPU에 올릴 파라메터, 이는 가변.
- 관찰값이 많은 것은 상관없어, 파라메터가 문제

In [63]:
a = tf.Variable([1,2,3,4])
id(a)

139920775946272

In [64]:
a.assign_add([-1,-2,-3,-4])
id(a)

139920775946272

메모리 주소 같은 모습

#### 요약 

`-` tf.Variable()로 만들어야 하는 뚜렷한 차이는 모르겠음. 

`-` 애써 tf.Variable()로 만들어도 간단한연산을 하면 그 결과는 tf.constant()로 만든 오브젝트와 동일해짐. 
- GPU에 메모리를 많이 올리지 않기 위해,

### 미분 

#### 모티브

`-` 예제: 컴퓨터를 이용하여 $x=2$에서 $y=3x^2$의 접선의 기울기를 구해보자. 

#### tf.GradientTape() 사용방법 

`-` 예제1: $x=2$에서 $y=3x^2$의 도함수값을 구하라. 

`-` 예제2: 조금 다른예제 

`-` 테이프의 개념 ($\star$)

(상황) 

우리가 어려운 미분계산을 컴퓨터에게 부탁하는 상황임. (예를들면 $y=3x^2$) 컴퓨터에게 부탁을 하기 위해서는 연습장(=테이프)에 $y=3x^2$이라는 수식을 써서 보여줘야하는데 이때 컴퓨터에게 target이 무엇인지 그리고 무엇으로 미분하고 싶은 것인지를 명시해야함. 

(1) `mytape = tf.GradientTape()`: 

(2) `mytape.__enter__()`: 

(3) `a=x/2*3; y=a*x**2`: 

(4) `mytape.__exit__(None,None,None)`:

(5) `mytape.gradient(y,x)`: 

`-` 예제3: 연습장을 언제 열고 닫을지 결정하는건 중요하다. 

`-` 예제4: with문과 함께 쓰는 tf.GradientTape()

`-` 예제5: 예제2를 with문과 함께 구현 

`-` 예제6: persistent = True

`-` 예제7: watch

`-` 예제9: 카페예제로 돌아오자. 

`-` 예제10: 카페예제의 매트릭스 버전 

`-` 예제11: 위의 예제에서 이론적인 $\boldsymbol{\beta}$의 최적값을 찾아보고 (즉 $\hat{\boldsymbol{\beta}}$을 찾고) 그곳에서 loss의 미분을 구하라. 구한결과가 $\begin{bmatrix}0 \\ 0 \end{bmatrix}$ 임을 확인하라. 