# 빅데이터 분석 특강 (2주차) 3월 14일 

- toc:true
- branch: master
- badges: true
- comments: false
- author: 최서연
- categories: [Special Topics in Big Data Analysis, 정규방정식, 벡터 미분, 매트릭스 미분]

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
tf.config.experimental.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

### tf.constant 

`-` 리스트

In [7]:
lst = [1,2,3,4,5,6]
lst

[1, 2, 3, 4, 5, 6]

In [8]:
lst[0]

1

In [9]:
lst[1]

2

In [10]:
lst[-1]

6

#### 예비학습: 중첩리스트 

`-` 아래는 일차원이지만 이차원으로 생각할 수 있다.

In [21]:
lst = [[1,2],[3,4]]

In [22]:
lst[0][1]

2

In [23]:
lst[1][0]

3

원소가 벡터이면 matrix로 생각 가능하다

```
1 2
3 4
```

In [26]:
print(lst[0][0]) # (1,1)
print(lst[0][1]) # (1,2)
print(lst[1][0]) # (2,1)
print(lst[1][1]) # (2,2)

1
2
3
4


In [27]:
lst

[[1, 2], [3, 4]]

In [28]:
np.array(lst)

array([[1, 2],
       [3, 4]])

`-` (4,1)  matrix 느낌의 list

In [30]:
[[1,2],[2,3],[3,4],[4,5]]

[[1, 2], [2, 3], [3, 4], [4, 5]]

In [34]:
lst = [[1],[2],[3],[4]] # (4,1) matrix = 길이가 4인 col-vector
lst

[[1], [2], [3], [4]]

In [33]:
np.array(lst)

array([[1],
       [2],
       [3],
       [4]])

`-` (1,4) 느낌의 list

In [36]:
lst = [[1,2,3,4]] # (1,4) matrix = 길이가 4인 row-vector
lst

[[1, 2, 3, 4]]

In [38]:
np.array(lst)

array([[1, 2, 3, 4]])

#### 선언

`-` 스칼라

In [43]:
tf.constant(3.14)

<tf.Tensor: shape=(), dtype=float32, numpy=3.14>

In [44]:
tf.constant(3.14) + tf.constant(3.14)

<tf.Tensor: shape=(), dtype=float32, numpy=6.28>

- 텐서플로로 꼭 바꿔줘야 함!

`-` 벡터

In [50]:
type(tf.constant(1)).shape

#### 타입

In [51]:
type(tf.constant([1,2,3]))

tensorflow.python.framework.ops.EagerTensor

- 자료형 확인

In [47]:
tf.constant(1)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [52]:
tf.constant([1,2,3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [53]:
_vector = tf.constant([1,2,3])

In [55]:
_vector[0]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

`-` 매트릭스

In [56]:
_matrix = tf.constant([[1,0],[0,1]])

In [57]:
_matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 0],
       [0, 1]], dtype=int32)>

3차원 이상의 배열은 tensor~

`-` array

In [65]:
np.array([[[0,1,1],[1,2,-1]],[[0,1,2],[1,2,-1]]])

array([[[ 0,  1,  1],
        [ 1,  2, -1]],

       [[ 0,  1,  2],
        [ 1,  2, -1]]])

In [64]:
np.array([[[0,1,1],[1,2,-1]],[[0,1,2],[1,2,-1]]]).shape

(2, 2, 3)

In [63]:
tf.constant(np.array([[[0,1,1],[1,2,-1]],[[0,1,2],[1,2,-1]]]))

<tf.Tensor: shape=(2, 2, 3), dtype=int64, numpy=
array([[[ 0,  1,  1],
        [ 1,  2, -1]],

       [[ 0,  1,  2],
        [ 1,  2, -1]]])>

#### 인덱싱 

In [66]:
_matrix = tf.constant([[1,2],[3,4]])
_matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [69]:
_matrix[0][0]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [70]:
_matrix[0]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [71]:
_matrix[0,:]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [72]:
_matrix[:,0]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 3], dtype=int32)>

- list 이기 때문에 

#### tf.constant는 불편하다. 

`-` 불편한 점
1. 모든 데이터 타입이 다 같아야 한다.
2. 원소 수정을 일부만 하는 것이 불가능하다
3. 묵시적 변환이 불가능하다

In [106]:
a = tf.constant([1,22,33])
a

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 1, 22, 33], dtype=int32)>

In [107]:
a[0]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [109]:
a[0] = [11]

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

In [110]:
1 + 3,14

(4, 14)

- int랑 float이랑 더하면 원래 int가 float으로 자동으로 바뀌어서 4.14로 계산되어야 하는 거 아닌가!

In [111]:
tf.constant(1.0)

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [112]:
tf.constant(3.14)

<tf.Tensor: shape=(), dtype=float32, numpy=3.14>

In [113]:
tf.constant(1.0) + tf.constant(3.14)

<tf.Tensor: shape=(), dtype=float32, numpy=4.1400003>

- 이제 되네~

`-` 같은 float도 안 되는 경우가 있음

In [114]:
tf.constant(1.0,dtype=tf.float64)

<tf.Tensor: shape=(), dtype=float64, numpy=1.0>

In [115]:
tf.constant(3.14)

<tf.Tensor: shape=(), dtype=float32, numpy=3.14>

In [116]:
tf.constant(1.0,dtype=tf.float64) + tf.constant(3.14)

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a double tensor but is a float tensor [Op:AddV2]

안 되는 모습!!

#### tf.constant $\to$ 넘파이 

---

In [117]:
np.array([3.14]) + np.array([1.0])

array([4.14])

In [118]:
tf.constant(np.array([3.14,-3.14]) + np.array([1,2]))

<tf.Tensor: shape=(2,), dtype=float64, numpy=array([ 4.14, -1.14])>

---

In [119]:
np.array(tf.constant(1)) # 방법 1

array(1, dtype=int32)

In [120]:
a = tf.constant(3.14)
type(a)

tensorflow.python.framework.ops.EagerTensor

In [121]:
a.numpy()

3.14

#### 연산

#### 형태변환

#### 선언고급 

#### tf.concat 

#### tf.stack 

#### tf.einsum

### tnp

#### tnp 사용방법 (불만해결방법)

#### 선언, 선언고급

#### 타입

#### tf.contant로 만들어도 마치 넘파이인듯 쓰는 기능들

#### 그렇지만 np.array는 아님 

### tf.Variable

#### 선언 

#### 타입

#### 인덱싱 

#### tf.Variable $\to$ 넘파이 

#### tf.Variable 도 불편하다. 

#### 연산 

#### 형태변환 

#### 선언고급 

#### tf.concat 

#### tf.stack

#### 심지어 tf.Variable()로 만들어진 오브젝트는 tnp의 효과(은총)도 받지 못함