# 빅데이터 분석 특강 (2주차) 3월 14일 

- toc:true
- branch: master
- badges: true
- comments: false
- author: 최서연
- categories: [Special Topics in Big Data Analysis, 정규방정식, 벡터 미분, 매트릭스 미분]

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
tf.config.experimental.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

### tf.constant 

`-` 리스트

In [7]:
lst = [1,2,3,4,5,6]
lst

[1, 2, 3, 4, 5, 6]

In [8]:
lst[0]

1

In [9]:
lst[1]

2

In [10]:
lst[-1]

6

#### 예비학습: 중첩리스트 

`-` 아래는 일차원이지만 이차원으로 생각할 수 있다.

In [21]:
lst = [[1,2],[3,4]]

In [22]:
lst[0][1]

2

In [23]:
lst[1][0]

3

원소가 벡터이면 matrix로 생각 가능하다

```
1 2
3 4
```

In [26]:
print(lst[0][0]) # (1,1)
print(lst[0][1]) # (1,2)
print(lst[1][0]) # (2,1)
print(lst[1][1]) # (2,2)

1
2
3
4


In [27]:
lst

[[1, 2], [3, 4]]

In [28]:
np.array(lst)

array([[1, 2],
       [3, 4]])

`-` (4,1)  matrix 느낌의 list

In [30]:
[[1,2],[2,3],[3,4],[4,5]]

[[1, 2], [2, 3], [3, 4], [4, 5]]

In [34]:
lst = [[1],[2],[3],[4]] # (4,1) matrix = 길이가 4인 col-vector
lst

[[1], [2], [3], [4]]

In [33]:
np.array(lst)

array([[1],
       [2],
       [3],
       [4]])

`-` (1,4) 느낌의 list

In [36]:
lst = [[1,2,3,4]] # (1,4) matrix = 길이가 4인 row-vector
lst

[[1, 2, 3, 4]]

In [38]:
np.array(lst)

array([[1, 2, 3, 4]])

#### 선언

`-` 스칼라

In [43]:
tf.constant(3.14)

<tf.Tensor: shape=(), dtype=float32, numpy=3.14>

In [44]:
tf.constant(3.14) + tf.constant(3.14)

<tf.Tensor: shape=(), dtype=float32, numpy=6.28>

- 텐서플로로 꼭 바꿔줘야 함!

`-` 벡터

In [50]:
type(tf.constant(1)).shape

#### 타입

In [51]:
type(tf.constant([1,2,3]))

tensorflow.python.framework.ops.EagerTensor

- 자료형 확인

In [47]:
tf.constant(1)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [52]:
tf.constant([1,2,3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [53]:
_vector = tf.constant([1,2,3])

In [55]:
_vector[0]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

`-` 매트릭스

In [56]:
_matrix = tf.constant([[1,0],[0,1]])

In [57]:
_matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 0],
       [0, 1]], dtype=int32)>

3차원 이상의 배열은 tensor~

`-` array

In [65]:
np.array([[[0,1,1],[1,2,-1]],[[0,1,2],[1,2,-1]]])

array([[[ 0,  1,  1],
        [ 1,  2, -1]],

       [[ 0,  1,  2],
        [ 1,  2, -1]]])

In [64]:
np.array([[[0,1,1],[1,2,-1]],[[0,1,2],[1,2,-1]]]).shape

(2, 2, 3)

In [63]:
tf.constant(np.array([[[0,1,1],[1,2,-1]],[[0,1,2],[1,2,-1]]]))

<tf.Tensor: shape=(2, 2, 3), dtype=int64, numpy=
array([[[ 0,  1,  1],
        [ 1,  2, -1]],

       [[ 0,  1,  2],
        [ 1,  2, -1]]])>

#### 인덱싱 

In [66]:
_matrix = tf.constant([[1,2],[3,4]])
_matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [69]:
_matrix[0][0]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [70]:
_matrix[0]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [71]:
_matrix[0,:]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [72]:
_matrix[:,0]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 3], dtype=int32)>

- list 이기 때문에 

#### tf.constant는 불편하다. 

`-` 불편한 점
1. 모든 데이터 타입이 다 같아야 한다.
2. 원소 수정을 일부만 하는 것이 불가능하다
3. 묵시적 변환이 불가능하다

In [106]:
a = tf.constant([1,22,33])
a

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 1, 22, 33], dtype=int32)>

In [107]:
a[0]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [109]:
a[0] = [11]

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

In [110]:
1 + 3,14

(4, 14)

- int랑 float이랑 더하면 원래 int가 float으로 자동으로 바뀌어서 4.14로 계산되어야 하는 거 아닌가!

In [111]:
tf.constant(1.0)

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [112]:
tf.constant(3.14)

<tf.Tensor: shape=(), dtype=float32, numpy=3.14>

In [113]:
tf.constant(1.0) + tf.constant(3.14)

<tf.Tensor: shape=(), dtype=float32, numpy=4.1400003>

- 이제 되네~

`-` 같은 float도 안 되는 경우가 있음

In [114]:
tf.constant(1.0,dtype=tf.float64)

<tf.Tensor: shape=(), dtype=float64, numpy=1.0>

In [115]:
tf.constant(3.14)

<tf.Tensor: shape=(), dtype=float32, numpy=3.14>

In [116]:
tf.constant(1.0,dtype=tf.float64) + tf.constant(3.14)

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a double tensor but is a float tensor [Op:AddV2]

안 되는 모습!!

#### tf.constant $\to$ 넘파이 

---

In [117]:
np.array([3.14]) + np.array([1.0])

array([4.14])

In [118]:
tf.constant(np.array([3.14,-3.14]) + np.array([1,2]))

<tf.Tensor: shape=(2,), dtype=float64, numpy=array([ 4.14, -1.14])>

---

In [119]:
np.array(tf.constant(1)) # 방법 1

array(1, dtype=int32)

In [120]:
a = tf.constant(3.14)
type(a)

tensorflow.python.framework.ops.EagerTensor

In [121]:
a.numpy()

3.14

#### 연산

In [123]:
a = tf.constant([1,2]) 
b = tf.constant([3,4])
a + b

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 6], dtype=int32)>

In [124]:
tf.add(a,b)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 6], dtype=int32)>

`-` 곱하기

In [136]:
a = tf.constant([[1,2],[3,4]])
b = tf.constant([[5,6],[7,8]])
a * b # 요소들의 곱

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 12],
       [21, 32]], dtype=int32)>

In [137]:
tf.multiply(a,b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 12],
       [21, 32]], dtype=int32)>

`-` 매트릭스의 곱

In [138]:
a = tf.constant([[1,0],[0,1]]) # (2,2)
b = tf.constant([[5],[7]]) # (2,1)
a @ b

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[5],
       [7]], dtype=int32)>

In [139]:
tf.matmul(a,b)

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[5],
       [7]], dtype=int32)>

`-` 역행렬 구하기

In [140]:
a = tf.constant([[1,0],[0,2]])
a

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 0],
       [0, 2]], dtype=int32)>

자료향이 int라서 에러가 떠~

In [141]:
tf.linalg.inv(a)

InvalidArgumentError: Value for attr 'T' of int32 is not in the list of allowed values: double, float, half, complex64, complex128
	; NodeDef: {{node MatrixInverse}}; Op<name=MatrixInverse; signature=input:T -> output:T; attr=adjoint:bool,default=false; attr=T:type,allowed=[DT_DOUBLE, DT_FLOAT, DT_HALF, DT_COMPLEX64, DT_COMPLEX128]> [Op:MatrixInverse]

In [142]:
a = tf.constant([[1.0,0.0],[0.0,2.0]])
a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 0.],
       [0., 2.]], dtype=float32)>

In [143]:
tf.linalg.inv(a)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1. , 0. ],
       [0. , 0.5]], dtype=float32)>

`-` `tf.linalg.` + `tab` 에서 응용해봐~

In [144]:
a = tf.constant([[1.0,2.0],[3.0,4.0]])
print(a)
tf.linalg.det(a)

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)


<tf.Tensor: shape=(), dtype=float32, numpy=-2.0>

In [145]:
tf.linalg.trace(a) # 대각선 원소들의 합

<tf.Tensor: shape=(), dtype=float32, numpy=5.0>

#### 형태변환

`-` 기본: `tf.reshape()` 를 이용

In [147]:
a = tf.constant([1,2,3,4])
a

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [148]:
tf.reshape(a,(4,1))

<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3],
       [4]], dtype=int32)>

shape바꿔주기 (4,1)에서 (1,4) 로~

In [149]:
tf.reshape(a,(2,2))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [150]:
tf.reshape(a,(2,2,1))

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

`-` 다차원

In [151]:
a = tf.constant([1,2,3,4,5,6,7,8,9,10,11,12])
a

<tf.Tensor: shape=(12,), dtype=int32, numpy=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int32)>

In [153]:
tf.reshape(a,(2,2,3))

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [154]:
tf.reshape(a,(4,3))

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

`-` `tf.resh`

-1을 쓰면 남은 차원을 알아서 계산을 해준다.
- 아래의 경우 4 쓰고 -1 쓰면 3으로 자동 계산되는 것~

In [157]:
tf.reshape(a,(4,-1))

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

아래의 경우 2,2,-1 쓰면 -1이 알아서 계산~

In [159]:
tf.reshape(a,(2,2,-1))

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [160]:
b = tf.reshape(a,(2,2,-1))
b

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

-1로 array 변경도 가능~

In [162]:
tf.reshape(b,-1)

<tf.Tensor: shape=(12,), dtype=int32, numpy=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int32)>

#### 선언고급 

`-` 다른 자료형 (리스트나 넘파이)로 만들고 바꾸는 것도 좋다.

In [164]:
np.diag([1,2,3,4]) # 대각행렬 만들어

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [166]:
tf.constant(np.diag([1,2,3,4])) # 텐서로도 만들어

<tf.Tensor: shape=(4, 4), dtype=int64, numpy=
array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])>

`-` `tf.ones`, `tf.zeros`

In [167]:
tf.zeros([3,3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

아래는 int로 나오고 위에는 float으로 나왔다~

In [171]:
tf.reshape(tf.constant([0]*9),(3,-1))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)>

`-` range(10)

In [185]:
a = range(0,12) # genrator야 range는

In [186]:
print(a)

range(0, 12)


In [187]:
a?

Type:        range
String form: range(0, 12)
Length:      12
Docstring:  
range(stop) -> range object
range(start, stop[, step]) -> range object

Return an object that produces a sequence of integers from start (inclusive)
to stop (exclusive) by step.  range(i, j) produces i, i+1, i+2, ..., j-1.
start defaults to 0, and stop is omitted!  range(4) produces 0, 1, 2, 3.
These are exactly the valid indices for a list of 4 elements.
When step is given, it specifies the increment (or decrement).


In [188]:
list(a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

array가 만들어진 모습

In [189]:
tf.constant(a)

<tf.Tensor: shape=(12,), dtype=int32, numpy=array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int32)>

In [191]:
list(range(0,5)) # 0,1,2,3,4

[0, 1, 2, 3, 4]

In [193]:
list(range(0,50,3)) # 3씩 건너서 만들어줘!

[0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48]

`-` `tf.linspace`

In [197]:
tf.linspace(0,1,10) # 0에서 1 사이의 10개 만들어줘!

<tf.Tensor: shape=(10,), dtype=float64, numpy=
array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])>

#### tf.concat 

#### tf.stack 

#### tf.einsum

### tnp

#### tnp 사용방법 (불만해결방법)

#### 선언, 선언고급

#### 타입

#### tf.contant로 만들어도 마치 넘파이인듯 쓰는 기능들

#### 그렇지만 np.array는 아님 

### tf.Variable

#### 선언 

#### 타입

#### 인덱싱 

#### tf.Variable $\to$ 넘파이 

#### tf.Variable 도 불편하다. 

#### 연산 

#### 형태변환 

#### 선언고급 

#### tf.concat 

#### tf.stack

#### 심지어 tf.Variable()로 만들어진 오브젝트는 tnp의 효과(은총)도 받지 못함